name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: "Этот PR не был активен долгое время и теперь признан устаревшим. Это означает то, что он может быть закрыт в течении ~ 7 дней, убедитесь, что Ваш PR был закончен и готов к работе. Если всё готово, но PR никто не смотрел, то необходимо запросить помощь мейнтенеров для решения проблемы. Как только закончите Ваши действия, сразу уведомите об этом мейнтенера для сброса таймера устаревания. Если Вам кажется, что никто не готов помочь, то вы можете закрыть данный PR самостоятельно, пока не объявится мейнтейнер, тогда будет возможность открыть данный PR снова."
        days-before-stale: 7
        days-before-close: 7
        stale-pr-label: '🕸️ устарело'
        exempt-pr-label: '⚠️ НЕ МЕРЖИТЬ ⚠️'
